### ISSUE TITLE
Roadmap / Tasks

### ISSUE THREAD

**Issue by HeikoKlare** [swt-initiative31/prototype-skija#14]
Since we are still in a prototyping phase, we have no defined roadmap towards a full implementation of SWT based on custom-implemented widgets rendered via Skia yet. 

Still, here we list several topics we need to test, address, or implement and which can be taken as a starting point for making contributions.

### Widgets
- [ ] Widget rendering/implementation: we currently have initial implementations for some widgets, but neither are those complete nor are all existing native widgets custom-implemented yet. The following list contains the native widgets and which of them already have at least partial custom implementations:
  - [x] Button
  - [ ] Canvas
  - [ ] Caret
  - [ ] ColorDialog/DirectoryDialog/FileDialog/FontDialog
  - [x] Combo
  - [ ] Composite
  - [ ] CoolBar/CoolItem
  - [ ] DateTime
  - [ ] ExpandBar/ExpandItem
  - [ ] Group
  - [x] Label
  - [ ] Link
  - [ ] List
  - [ ] Menu/MenuItem
  - [ ] MessageBox
  - [ ] ProgressBar
  - [ ] Sash
  - [ ] Scale
  - [ ] Scrollable/Scrollbar
  - [ ] Slider
  - [ ] Spinner
  - [ ] TabFolder/TabItem
  - [x] Table/TableColumn/TableItem
  - [x] Text
  - [ ] ToolBar/ToolItem
  - [ ] Tree/TreeColumn/TreeItem
- [ ] OS-independent event handling: the event handling for widgets is currently realized by the existing native event handling of the OS. At the end, this needs to be replaced via an independent event handling. To this end, options for realizing the event handling should be evaluated. A good starting point could be one of the already custom-implemented widgets (like the `Button`) being used in an independent snippet that is finally run without any native code but just based on a custom event queue/handling.

### `SkijaGC`
- [ ] `SkijaGC` implementation: The `SkijaGC` is currently implemented to the extent that is required for implementing the widgets we have addressed so far. At the end, the `SkijaGC` should provide the same capabilities as the original native `GC` implementations. As the `SkijaGC` can be used even independent from widgets being rendered with it, e.g., for just rendering performance-critical parts like diagrams, extending its implementation is a valuable task on its own.
- [ ] `SkijaGC` efficiency: the `SkijaGC` currently renders each widgetsinto its own surface, which is created anew for each rendering operation, and then copies over the results to the original `GC`. This is inefficient and potential improvements should be evaluated in two directions:
   - [ ] Reuse the rendering surface across multiple rendering operations of the same widget.
   - [ ] Directly render into the buffer used by the native GC instead of copying the result from the Skija surface to the native GC. There are already experiments to do this via a GLCanvas (#8), but it would also be interested to evaluate whether this is possible without OpenGL capabilities.

### Performance-Critical Rendering
- [ ] Diagram rendering support with Skia: Diagram frameworks like [GEF Classic ](https://github.com/eclipse-gef/gef-classic) (and its core component draw2d) only use functionality of the `GC` to rendering complex diagrams. Using Skia for this instead can provide a significant performance improvement and can make diagram rendering more independent from native APIs. To this end, Draw2D/GEF Classic or other diagram framework can be adapted to use a `SkijaGC`.

### Misc
- [ ] Linux support: the current custom-implemented widgets are only adapted for Windows and MacOS. The implementation should also be extended to work on Linux.
- [ ] CI: we currently do not have any CI testing the custom-implemented widgets. Even though the state of the widgets is probably not sufficient to make every existing test work, it would be useful to have some continuous feedback on changes via CI, also to see the state of work on the different OSes. Just running the GitHub actions workflows of SWT for the fork could be a good starting point.

**Comment by DieterMai** [comment]
I'm planning to implement the widget "Scale". I thing this is a fairly simple widget that will be a great exercise to see how skija rendering works.

As soon as i have some progress, will create an issue for this (like proposed in the weekly today)

**Comment by DieterMai** [comment]
I started working on ToolBar/ToolItem

**Comment by vogella** [comment]
Question: Will the Skia implementation still use native handlers? I have a client with lots of tabs,labels, text and links on these tabs. We can currently only open around ~150 of these UI elements before running in the no-more-handlers exception (set in Windows 11 to its max value). If the new implementation would not have this limitation that would be great news for this client.

**Comment by HeikoKlare** [comment]
> Question: Will the Skia implementation still use native handlers?

Do you mean handlers or handles? Regarding handles: since most of the native widgets and other resources (like images, fonts etc.) are replaced with objects "inside" Skia, the issue with running out of handles on Windows should be resolved.

**Comment by tmssngr** [comment]
> Question: Will the Skia implementation still use native handlers? I have a client with lots of tabs,labels, text and links on these tabs. We can currently only open around ~150 of these UI elements before running in the no-more-handlers exception (set in Windows 11 to its max value). If the new implementation would not have this limitation that would be great news for this client.

I remember similar problems in the past where we used a menu to select branches in our SWT based Git client. Some users with large repositories had crashes. The last days I've experimented with "light-weight" controls similar to Swing controls that could be nested in light-weight containers to only have one heavy-weight control (Shell) left. @DenisUngemach is already working on something similar and we want to unify the best of our approaches.

**Comment by vogella** [comment]
> > Question: Will the Skia implementation still use native handlers?
> 
> Do you mean handlers or handles? Regarding handles: since most of the native widgets and other resources (like images, fonts etc.) are replaced with objects "inside" Skia, the issue with running out of handles on Windows should be resolved.

Thanks, yes handles. That are really good news.

**Comment by claesrosell** [comment]
I will begin to implement the ProgressBar

**Comment by DieterMai** [comment]
I will takle Tree/TreeColumn/TreeItem next

**Comment by HeikoKlare** [comment]
> I will takle Tree/TreeColumn/TreeItem next

Thank you, @DieterMai !
I just want to mention for such complex widgets as Tree, it might make sense to have a look the Nebula widget library as it also contains sophisticated custom widget implementation (e.g., this is the tree: https://github.com/EclipseNebula/nebula/tree/master/widgets/ctree). Just to avoid that we invest much effort into reimplementing widgets for which an implementation (at least one to start with) already exists.

**Comment by raghucssit** [comment]
I will work on ProgressBar. I have updated the Widgets list above.

**Comment by HeikoKlare** [comment]
To avoid duplicate efforts: @claesrosell also [wrote that he will work on ProgressBar](https://github.com/swt-initiative31/prototype-skija/issues/14#issuecomment-2670718736) (see also https://github.com/swt-initiative31/prototype-skija/issues/100). Is that information still up-to-date?

**Comment by claesrosell** [comment]
> To avoid duplicate efforts: [@claesrosell](https://github.com/claesrosell) also [wrote that he will work on ProgressBar](https://github.com/swt-initiative31/prototype-skija/issues/14#issuecomment-2670718736) (see also [#100](https://github.com/swt-initiative31/prototype-skija/issues/100)). Is that information still up-to-date?

I still intend to finish the ProgressBar. I have the animation of the SWT.INDETERMINATE mode left to implement, though. @raghucssit, if you could pick another widget, I would appreciate it. If you really want to implement the ProgressBar, I can pick something else.

**Comment by raghucssit** [comment]
@claesrosell No Problem. You can continue work on ProgressBar.. I will pick Slider widget.

**Comment by ddscharfe** [comment]
I’m starting to work on Diagram rendering support with Skia. @azoitl, IIRC you were interested in this as well - have you looked into it yet?

@HeikoKlare the performance issue mentioned in https://github.com/swt-initiative31/prototype-skija/issues/12#issuecomment-2703942293 seems highly relevant here.

**Comment by azoitl** [comment]
> I’m starting to work on Diagram rendering support with Skia. [@azoitl](https://github.com/azoitl), IIRC you were interested in this as well - have you looked into it yet?

Yes I have looked into it. I have a first very rough prototype where I can run at least one Draw2d Example. I will be in tomorrows meeting and I can show you where I I'm and share my code if you like.

> [@HeikoKlare](https://github.com/HeikoKlare) the performance issue mentioned in [#12 (comment)](https://github.com/swt-initiative31/prototype-skija/issues/12#issuecomment-2703942293) seems highly relevant here.

I also experimented with a dedicated GL Canvas to get more performance. But not sure if this is still working. It was based on a very old branch from @HeikoKlare. I also didn't do any performance measurements.

**Comment by ddscharfe** [comment]
> > I’m starting to work on Diagram rendering support with Skia. [@azoitl](https://github.com/azoitl), IIRC you were interested in this as well - have you looked into it yet?
> 
> Yes I have looked into it. I have a first very rough prototype where I can run at least one Draw2d Example. I will be in tomorrows meeting and I can show you where I I'm and share my code if you like.

Great! Looking forward to seeing your progress tomorrow.

**Comment by lathapatil** [comment]
I will start working on Sash widget .

**Comment by fedejeanne** [comment]
> I will start working on Sash widget .

Thank you! Let me know when you create an issue/PR and I'll link it in the description.

**Comment by raghucssit** [comment]
I will work on TabFolder/TabItem
https://github.com/swt-initiative31/prototype-skija/issues/177

**Comment by deepika-u** [comment]
I will start with DateTime.

**Comment by lathapatil** [comment]
I will start working on  `Scrollable`/`Scrollbar `

**Comment by raghucssit** [comment]
I will start working on `CoolBar/CoolItem`

**Comment by raghucssit** [comment]
> > I will start working on `CoolBar/CoolItem`
> 
> Thank you! Note that for `CoolBar`/`CoolItem` there is already an emulated implementation used for Linux and MacOS. So we can probably just use that one on Windows as well and throw away the native implementation.

Thanks.. I will take a look at emulated and try to refactor it as per need.

**Comment by raghucssit** [comment]
I will work on MessageBox. Plan is to use a shell and layout needed widgets.

**Comment by raghucssit** [comment]
I have created PR for MessageBox.. I will work on ExpandBar/ExpandItem

**Comment by raghucssit** [comment]
I will port FileDialog to platform independent implementation

**Comment by tmssngr** [comment]
IMHO the file/directory dialog can remain as is. Better stick with the native one because they are too platform-specific anyway.

**Comment by raghucssit** [comment]
> IMHO the file/directory dialog can remain as is. Better stick with the native one because they are too platform-specific anyway.

Ok sure.. Then I will start with ColorDialog.. That should be ok because i can populate blocks and set colors to choose..
